services:
  db:
    image: postgres:16
    container_name: library_postgres
    restart: always
    environment:
      POSTGRES_USER: library_user
      POSTGRES_PASSWORD: library_pass
      POSTGRES_DB: library_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U library_user -d library_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    build: .
    container_name: library_api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://library_user:library_pass@db:5432/library_db
      LOG_LEVEL: info
      LOG_DIR: logs
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: